---
- name: Grabbing logs
  hosts: quiz
  
  tasks:
    - name: Grab last 20 lines from inventory logs
      shell: |
        grep 'Ultradns quiz application took' /var/log/ultradns-quiz-madeup.log | tail -20
      register: output

    - name: Extract ms from logs
      shell: |
        echo "{{ log_lines.stdout }}" | grep -oP 'took \K[0-9]+'
      register: milliseconds
      delegate_to: localhost

    - name: Send ms to temp file
      copy:
        content: "{{ milliseconds.stdout }}"
        dest: ""

    - name: Log output
      debug:
        msg: 
          - "Server: {{ inventory_hostname }}"
          - "Last 20 log entries:"
          - "{{ output.stdout_lines }}"

    - name: Save results to local file
      delegate_to: localhost
      copy:
        content: |
          ========================================
          Server: {{ inventory_hostname }}
          ========================================
          {{ output.stdout }}
        dest: "./logs/{{ inventory_hostname }}.txt"