---
- name: Grabbing logs
  hosts: quiz
  vars:
    temp_dir: /etc/Projects/ansible/temp
    output_dir: /etc/Projects/ansible/output
    ansible_home: /etc/Projects/ansible
  tasks:
    - name: Grab last 20 lines from inventory logs
      shell: |
        grep 'Ultradns quiz application took' /var/log/ultradns-quiz-madeup.log | tail -20
      register: output

    - name: Extract ms from logs
      shell:  |
        echo "{{ output.stdout }}" | grep -oP 'took \K[0-9]+'
      register: milliseconds
      delegate_to: localhost

    - name: Send ms to temp file
      copy:
        content: "{{ milliseconds.stdout }}"
        dest: "{{ temp_dir }}/ms_{{ inventory_hostname }}.txt"
      delegate_to: localhost

    - name: Calculate stats
      shell:  |
        {{ ansible_home }}/stats.py < {{ temp_dir }}/ms_{{ inventory_hostname }}.txt
      register: server_stats
      delegate_to: localhost

    - name: Log output
      debug:
        msg: 
          - "Server: {{ inventory_hostname }}"
          - "Last 20 log entries:"
          - "{{ server_stats.stdout_lines }}"

    - name: Also sending to output file
      copy:
        content: "{{ server_stats.stdout_lines }}"
        dest: "{{ output_dir }}/ms_{{ inventory_hostname }}.txt"
      delegate_to: localhost